"""initial Agent schema"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cornagent_agent_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("owner_membership_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("active_leaf_message_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_cornagent_agent_sessions_owner_updated",
        "cornagent_agent_sessions",
        ["tenant_id", "owner_membership_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "cornagent_agent_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("owner_membership_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.Column("content_parts", sa.JSON(), nullable=False),
        sa.Column("provider_messages", sa.JSON(), nullable=False),
        sa.Column("parent_message_id", sa.String(length=36), nullable=True),
        sa.Column("version_group_id", sa.String(length=36), nullable=False),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.Column("supersedes_message_id", sa.String(length=36), nullable=True),
        sa.Column("process_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("process_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('user', 'assistant')", name="ck_cornagent_agent_messages_role"
        ),
        sa.CheckConstraint("version_index >= 1", name="ck_cornagent_agent_messages_version_index"),
        sa.ForeignKeyConstraint(
            ["parent_message_id"], ["cornagent_agent_messages.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["cornagent_agent_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_message_id"], ["cornagent_agent_messages.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "version_group_id", "version_index", name="uq_cornagent_agent_message_version"
        ),
    )
    op.create_index(
        "ix_cornagent_agent_messages_session_created",
        "cornagent_agent_messages",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cornagent_agent_messages_version_group_id"),
        "cornagent_agent_messages",
        ["version_group_id"],
        unique=False,
    )
    op.create_table(
        "cornagent_files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("agent_session_id", sa.String(length=36), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=160), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("storage_key", sa.String(length=320), nullable=False),
        sa.Column("uploaded_by", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("inspection_status", sa.String(length=24), nullable=False),
        sa.Column("extraction_status", sa.String(length=24), nullable=False),
        sa.Column("extracted_markdown", sa.Text(), nullable=True),
        sa.Column("extraction_parser", sa.String(length=64), nullable=True),
        sa.Column("extraction_parser_version", sa.String(length=32), nullable=True),
        sa.Column("extracted_sha256", sa.String(length=64), nullable=True),
        sa.Column("extracted_size_bytes", sa.Integer(), nullable=True),
        sa.Column("extraction_truncated", sa.Boolean(), nullable=False),
        sa.Column("extraction_error_code", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "extraction_status <> 'ready' OR (extracted_markdown IS NOT NULL "
            "AND extraction_parser IS NOT NULL AND extraction_parser_version IS NOT NULL "
            "AND extracted_sha256 IS NOT NULL AND extracted_size_bytes IS NOT NULL)",
            name="ck_cornagent_files_extracted_content",
        ),
        sa.CheckConstraint(
            "extraction_status IN ('not_requested', 'pending', 'ready', 'failed')",
            name="ck_cornagent_files_extraction_status",
        ),
        sa.CheckConstraint(
            "inspection_status IN ('pending', 'validated', 'rejected', 'error')",
            name="ck_cornagent_files_inspection_status",
        ),
        sa.CheckConstraint("purpose = 'session_attachment'", name="ck_cornagent_files_purpose"),
        sa.CheckConstraint(
            "state <> 'ready' OR agent_session_id IS NOT NULL", name="ck_cornagent_files_owner"
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'stored', 'ready', 'delete_pending', 'deleted')",
            name="ck_cornagent_files_state",
        ),
        sa.CheckConstraint(
            "state NOT IN ('stored', 'ready') OR (sha256 IS NOT NULL AND size_bytes IS NOT NULL)",
            name="ck_cornagent_files_content",
        ),
        sa.ForeignKeyConstraint(
            ["agent_session_id"], ["cornagent_agent_sessions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_cornagent_files_agent_session_state",
        "cornagent_files",
        ["tenant_id", "agent_session_id", "state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cornagent_files_tenant_id"), "cornagent_files", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_cornagent_files_unclaimed", "cornagent_files", ["state", "created_at"], unique=False
    )
    op.create_table(
        "cornagent_agent_message_files",
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("position >= 0", name="ck_cornagent_agent_message_files_position"),
        sa.ForeignKeyConstraint(["file_id"], ["cornagent_files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["message_id"], ["cornagent_agent_messages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("message_id", "file_id"),
        sa.UniqueConstraint(
            "message_id", "position", name="uq_cornagent_agent_message_file_position"
        ),
    )
    op.create_index(
        "ix_cornagent_agent_message_files_file_id",
        "cornagent_agent_message_files",
        ["file_id"],
        unique=False,
    )
    op.create_table(
        "cornagent_agent_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("owner_membership_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("user_message_id", sa.String(length=36), nullable=False),
        sa.Column("assistant_message_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("draft_markdown", sa.Text(), nullable=False),
        sa.Column("reasoning_markdown", sa.Text(), nullable=False),
        sa.Column("content_parts", sa.JSON(), nullable=False),
        sa.Column("provider_usage", sa.JSON(), nullable=False),
        sa.Column("checkpoint", sa.JSON(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("stream_epoch", sa.Integer(), nullable=False),
        sa.Column("next_sequence", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_fence", sa.BigInteger(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_wait_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('create', 'regenerate')", name="ck_cornagent_agent_runs_kind"),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'waiting_for_user', 'cancelling', "
            "'completed', 'failed', 'cancelled')",
            name="ck_cornagent_agent_runs_status",
        ),
        sa.CheckConstraint("attempt >= 0", name="ck_cornagent_agent_runs_attempt"),
        sa.CheckConstraint("next_sequence >= 1", name="ck_cornagent_agent_runs_next_sequence"),
        sa.CheckConstraint("stream_epoch >= 1", name="ck_cornagent_agent_runs_stream_epoch"),
        sa.ForeignKeyConstraint(
            ["assistant_message_id"], ["cornagent_agent_messages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["cornagent_agent_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_message_id"], ["cornagent_agent_messages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_cornagent_agent_runs_assistant_message_id",
        "cornagent_agent_runs",
        ["assistant_message_id"],
        unique=False,
    )
    op.create_index(
        "ix_cornagent_agent_runs_recovery",
        "cornagent_agent_runs",
        ["status", "lease_expires_at", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_cornagent_agent_runs_active_session",
        "cornagent_agent_runs",
        ["session_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('pending', 'running', 'waiting_for_user', 'cancelling')"
        ),
        sqlite_where=sa.text("status IN ('pending', 'running', 'waiting_for_user', 'cancelling')"),
    )
    op.create_table(
        "cornagent_agent_questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("owner_membership_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("tool_call_id", sa.String(length=255), nullable=False),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("selected_option_id", sa.String(length=64), nullable=True),
        sa.Column("answer_content", sa.Text(), nullable=True),
        sa.Column("tool_result", sa.JSON(), nullable=False),
        sa.Column("resume_payload", sa.JSON(), nullable=False),
        sa.Column("response_idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("response_request_hash", sa.String(length=64), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'answered', 'cancelled')",
            name="ck_cornagent_agent_questions_status",
        ),
        sa.CheckConstraint("tool_name = 'ask_user'", name="ck_cornagent_agent_questions_tool_name"),
        sa.ForeignKeyConstraint(["run_id"], ["cornagent_agent_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["cornagent_agent_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "tool_call_id", name="uq_cornagent_agent_question_tool_call"),
    )
    op.create_index(
        "uq_cornagent_agent_questions_pending_run",
        "cornagent_agent_questions",
        ["run_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
        sqlite_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_cornagent_agent_questions_pending_run",
        table_name="cornagent_agent_questions",
        postgresql_where=sa.text("status = 'pending'"),
        sqlite_where=sa.text("status = 'pending'"),
    )
    op.drop_table("cornagent_agent_questions")
    op.drop_index(
        "uq_cornagent_agent_runs_active_session",
        table_name="cornagent_agent_runs",
        postgresql_where=sa.text(
            "status IN ('pending', 'running', 'waiting_for_user', 'cancelling')"
        ),
        sqlite_where=sa.text("status IN ('pending', 'running', 'waiting_for_user', 'cancelling')"),
    )
    op.drop_index("ix_cornagent_agent_runs_recovery", table_name="cornagent_agent_runs")
    op.drop_index("ix_cornagent_agent_runs_assistant_message_id", table_name="cornagent_agent_runs")
    op.drop_table("cornagent_agent_runs")
    op.drop_index(
        "ix_cornagent_agent_message_files_file_id", table_name="cornagent_agent_message_files"
    )
    op.drop_table("cornagent_agent_message_files")
    op.drop_index("ix_cornagent_files_unclaimed", table_name="cornagent_files")
    op.drop_index(op.f("ix_cornagent_files_tenant_id"), table_name="cornagent_files")
    op.drop_index("ix_cornagent_files_agent_session_state", table_name="cornagent_files")
    op.drop_table("cornagent_files")
    op.drop_index(
        op.f("ix_cornagent_agent_messages_version_group_id"), table_name="cornagent_agent_messages"
    )
    op.drop_index(
        "ix_cornagent_agent_messages_session_created", table_name="cornagent_agent_messages"
    )
    op.drop_table("cornagent_agent_messages")
    op.drop_index(
        "ix_cornagent_agent_sessions_owner_updated", table_name="cornagent_agent_sessions"
    )
    op.drop_table("cornagent_agent_sessions")
    # ### end Alembic commands ###
